import type { Metadata } from "next";
import { Island_Moments, Poppins, Inter, Jost } from "next/font/google";
import { Footer } from "@/components/Footer";
import "./globals.css";

const islandMoments = Island_Moments({
  weight: "400",
  variable: "--font-island-moments",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const jost = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${islandMoments.variable} ${poppins.variable} ${inter.variable} ${jost.variable} antialiased flex flex-col min-h-screen`}>
        <main className="flex-1">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
